
default_platform(:android)

platform :android do
  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "Submit a new Beta Build to Crashlytics Beta"
  lane :beta do
    gradle(task: "clean assembleRelease")
    crashlytics

    # sh "your_script.sh"
    # You can also use other beta testing services here
  end

  desc "Deploy a new version to the Diawai"
  lane :deploy do
    gradle(task: "clean assembleRelease")
    puts "APK path is: #{Actions.lane_context[SharedValues::GRADLE_APK_OUTPUT_PATH]}"

    diawi(token: '5Jg8WUU3fYFO8qLvcEb43waeDqZ3vcvkPsqFRAiDtp', file: "/Users/jason/.jenkins/workspace/QuanLyPhongTro/app/build/outputs/apk/release/app-release-unsigned.apk")

    diawiLink = "/Users/jason/.jenkins/workspace/QuanLyPhongTro/app/build/outputs/apk/release/app-release-unsigned.apk"

    msg = "test"
  end
end
