
default_platform(:android)

platform :android do
  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "Submit a new Beta Build to Crashlytics Beta"
  lane :beta do
    gradle(task: "clean assembleRelease")
    crashlytics

    # sh "your_script.sh"
    # You can also use other beta testing services here
  end

  desc "Deploy a new version to the Diawai"
  lane :deploy do
    gradle(task: "clean assembleRelease")
      api_token = "5Jg8WUU3fYFO8qLvcEb43waeDqZ3vcvkPsqFRAiDtp"

      APK_PATH = "/Users/jason/Desktop/build/fastlane"
        diawi(
          file: lane_context[SharedValues::GRADLE_APK_OUTPUT_PATH]
        )

        diawiLink = lane_context[SharedValues::APK_PATH]
        msg = "Get new #{ENV["APP_NAME"]} #{android_get_version_name} from: #{diawiLink}"
  end
end
