
default_platform(:android)

platform :android do
  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "Submit a new Beta Build to Crashlytics Beta"
  lane :beta do
    gradle(task: "clean assembleRelease")
    crashlytics

    # sh "your_script.sh"
    # You can also use other beta testing services here
  end

  desc "Deploy a new version to the Diawai"
  lane :deploy do
   gradle(
        task: "clean assemble",
        print_command: true,
        properties: {
          "android.injected.signing.store.file" => "/Users/jason/Desktop/keystore",
          "android.injected.signing.store.password" => "123123",
          "android.injected.signing.key.alias" => "123123",
          "android.injected.signing.key.password" => "123123",
        }
      )
      puts "APK path is: #{Actions.lane_context[SharedValues::GRADLE_APK_OUTPUT_PATH]}"

      APK_PATH = "./app/build/outputs/apk/local/debug/#{ENV["APP_NAME"]}"
      diawi(
        token: "ef09uCShuXV1bpvABrWm48SuBxvgcfeuKz0XSKZpQ0",
        file: lane_context[SharedValues::GRADLE_APK_OUTPUT_PATH]
      )

      diawiLink = lane_context[SharedValues::UPLOADED_FILE_LINK_TO_DIAWI]
      msg = "Get new #{ENV["APP_NAME"]} #{android_get_version_name} from: #{diawiLink}"
  end
end
